=== MauroPB30/M0373_XML_DTD/contacto.dtd
<!ELEMENT libreta_contactos (contacto+)>
<!ELEMENT contacto (edad?, nombre, apellidos,telefonos,email?,direccion)>
<!ATTLIST contacto es_familiar (si|no) #REQUIRED>
<!-- Si quiero indicar que es cualquier valor coloco CDATA sin parentesis donde esta primero|segundo -->
<!ELEMENT edad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT apellidos (apellido+)>
<!ELEMENT apellido (#PCDATA)>
<!ATTLIST apellido order (uno|dos) #REQUIRED>

<!ELEMENT telefonos (fijo,movil)>
<!ELEMENT fijo (#PCDATA)>
<!ELEMENT movil (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT direccion (calle, numero, piso?,puerta?,cp,ciudad)>
<!ATTLIST direccion domicilio (principal|secundaria) #REQUIRED>

<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT puerta (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== MauroPB30/M0373_XML_DTD/contacto.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE libreta_contactos SYSTEM "contacto.dtd">
<!-- Crear un document en XML vàlid amb la informació d’un únic contacte.
1.2 Modela como a mínim la següent informació:
1.3 Modifica el document afegir la següent informació:
1.4 Modifica el document per que pugui emmagatzemar 2 contactes.
1.5 Afegeix un atribut que ens indiqui si un contacte es un familiar o no, i si una direcció es el
domicili principal o no.-->
<libreta_contactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="contacto.xsd"
>
    
<contacto es_familiar="si">
    <edad>34</edad>
    <nombre>Dario</nombre>
    <apellidos>
        <apellido order="uno"> Patiño</apellido>
        <apellido order="dos"> Blanco</apellido>
    </apellidos>
    <telefonos>
        <fijo>937449559</fijo>
        <movil>671510410</movil>
    </telefonos>
    <email>
        DarioP@correo.com
    </email>
    <direccion domicilio="principal">
        <calle>C/ Pelai</calle>
        <numero>12</numero>
        <piso>2</piso>
        <puerta>23</puerta>
        <cp>08920</cp>
        <ciudad>Barcelona</ciudad>
    </direccion>
</contacto>

<contacto es_familiar="no">
    <edad>34</edad>
    <nombre> Mauricio</nombre>
    <apellidos>
        <apellido order="uno"> Patiño</apellido>
        <apellido order="dos"> Blanco</apellido>
    </apellidos>
    <telefonos>
        <fijo>937444559</fijo>
        <movil>671519810</movil>
    </telefonos>
    <email>
        MauricioP@correo.com
    </email>
    <direccion domicilio="secundaria">
        <calle>c\ Pelai</calle>
        <numero>12</numero>
        <piso>2</piso>
        <puerta>23</puerta>
        <cp>08920</cp>
        <ciudad>Barcelona</ciudad>
    </direccion>
</contacto>
</libreta_contactos>
