=== MauroPB30/M0373_XML_DTD/Grupo_Musica.dtd
<!ELEMENT Grupos_musica (grupo+)>

<!ELEMENT grupo (nombre, genero+, web?, integrantes, conciertos*, fans)>
<!ATTLIST grupo numero_integrantes CDATA #REQUIRED>
<!ATTLIST grupo genero_principal (rock|pop|trap|classic) #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT web (#PCDATA)>

<!ELEMENT integrantes (integrante+)>
<!ELEMENT integrante (nombre, apellido)>
<!ATTLIST integrante id CDATA #REQUIRED>

<!ELEMENT apellido (#PCDATA)>

<!ELEMENT conciertos (#PCDATA)>
<!ELEMENT fans (#PCDATA)>

=== MauroPB30/M0373_XML_DTD/Grupos_Musica.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE Grupos_musica SYSTEM "Grupo_Musica.dtd">

<Grupos_musica>

    <grupo numero_integrantes="5" genero_principal="rock">
        <nombre>ACDC</nombre>
        <genero>Rock</genero>
        <web>https://www.acdc.com/home/</web>

        <integrantes>
            <integrante id="1">
                <nombre>Brian</nombre>
                <apellido>Johnson</apellido>
            </integrante>
            <integrante id="2">
                <nombre>Angus</nombre>
                <apellido>Young</apellido>
            </integrante>
        </integrantes>

        <conciertos>150</conciertos>
        <fans>159400000</fans>
    </grupo>

    <grupo numero_integrantes="5" genero_principal="classic">
        <nombre>Binomio de Oro</nombre>
        <genero>Vallenato</genero>
        <web>https://www.youtube.com/@binomiodeorooficial</web>

        <integrantes>
            <integrante id="1">
                <nombre>Jean Carlos</nombre>
                <apellido>Centeno</apellido>
            </integrante>
            <integrante id="2">
                <nombre>Israel</nombre>
                <apellido>Romero</apellido>
            </integrante>
        </integrantes>

        <conciertos>250</conciertos>
        <conciertos>300</conciertos>
        <fans>20400000</fans>
    </grupo>

</Grupos_musica>
